let flag = {value: 0}

let binanceArr = {data: []}
let mexcArr = {data: []}
let bybitArr = {data: []}
let gateIoArr = {data: []}
let coinbaseArr = {data: []}
let lbankArr = {data: []}
let kucoinArr = {data: []}
let okxArr = {data: []}
let bitgetArr = {data: []}
let huobiArr = {data: []}
let poloniexArr = {data: []}
let bitmartArr = {data: []}

const mexcBlackList = ['MULTIUSDT', 'RUNEUSDT', 'MDXUSDT', ]
const binanceBlackList = ['AXSBIDR', 'NBTBIDR', 'NBTUSDT', 'MULTIUSDT', 'RUNEUSDT', 'MDXUSDT', ]
const bybitBlackList = ['DASHUSDT', 'ZECUSDT', 'TOMSUSDT', 'RUNEUSDT', ]
const gateIoBlackList = []
const lbankBlackList = ['IDUSDT', ]
const kucoinBlackList = ["JUPETH","POWRUSDT","ALBTUSDT","GOUSDT","CHSBBTC","TKOBTC","PIVXBTC","POWRBTC","ITAMCUBEUSDT","USDTPAX","EPSBTC","SPELLUSDT","FCDUSDT","BNTUSDT","TOMOBTC","BNTBTC","BCDETH","UDOOETH","GHSTUSDT","CXOETH","XSRUSDT","HORDUSDT","CSBTC","TOMOUSDT","RPCUSDT","BAKEETH","TKYBTC","PLATOUSDT","BAKEBTC","BURPUSDT","AIONBTC","CSPETH","GOETH","CXOBTC","BNTETH","CARRUSDT","EPSUSDT","BADGERBTC","WNXMBTC","CVBTC","BETAUSDT","MHCBTC","DGTXETH","WNCGBTC","SUSDETH","SNTVTETH","TCPUSDT","RPCETH","ETHOUSDT","PPTETH","PRMXUSDT","MFTUSDT","SNTBTC","REPETH","DATXETH","BCDBTC","NIFUSDT","CBCBTC","MHCUSDT","MXWUSDT","POWRETH","SUSDUSDT","FCLETH","CBCUSDT","CSETH","PIVXETH","RBTCBTC","DATXBTC","ALBTETH","UMBUSDT","SDNETH","DPIUSDT","DINOUSDT","KINUSDT","IDEXUSDT","WNCGUSDT","TKOUSDT","TKYETH","PIVXUSDT","LYXEUSDT","MBOXUSDT","REPUSDT","SDNUSDT","TOMOETH","NFTBUSDT","CARRBTC","TKYUSDT","PPTBTC","RIFBTC","EXRDUSDT","COMBUSDT","CVETH","CEURBTC","DGTXBTC","SOVUSDT","BADGERUSDT","DORAUSDT","MFTBTC","GOBTC","XVSUSDT","SPIUSDT","GHSTBTC","SUSDBTC","BAKEUSDT","LYXEETH","OOKIUSDT","CSPBTC","CEURUSDT","RBSUSDT","JUPUSDT","OOKIBTC","GPTUSDT","SNTVTBTC","STMXUSDT","BMONUSDT","REPBTC","USDNUSDT","UBXTUSDT","ETHOBTC","COCOSUSDT","SNTETH","SRBSUSDT","CHSBETH","FCLUSDT","DORABTC","AIONETH","WNXMUSDT","MHCETH","ALPACAUSDT","KP3RUSDT","SURVUSDT","MBOXBTC","XVSBTC","LOKIBTC","MATICUST","TEMUSDT",'FKXUSDT','PCXUSDT','JARBTC','FKXETH','GMBBTC','HAWKUSDT','SHXBTC','EFXBTC','FKXBTC', 'QUARTZUSDT', 'MODEFIBTC','EDGBTC','UBXUSDT','EFXUSDT','PIASUSDT','APLBTC','SLCLUSDT','CIX100USDT','PLAYBTC','OPCTBTC','CPCETH']
const huobiBlackList = ['F1F2X8Z9', 'A8S8D8F8','H9H9X6Z7', 'A8S83LD8F8','H8H8X6Z7', 'TRX3SUSDT','W4J4X8Z9', 'E9F9X8Z9','C1D1X6Z7', 'H3H3X8Z9','Q1W2X8Z9', 'A8S83SD8F8','Y1Y2X8Z9', 'TRX3LUSDT','H6H6X6Z7', 'A3B4X8Z9','A3B4X6Z7']
const bitgetBlackList = ['SBTCSUSDT', 'SETHSBTC']
const poloniexBlackList = [' XRPBULLUSDT', 'CVTBTC', 'CVTUSDT', 'LIVEUSDT', 'MIDWITUSDT', 'POLOTEST2POLOTEST1', 'POLOTEST3POLOTEST4', 'POLOTEST2POLOTEST4', 'POLOTEST2POLOTEST3', 'POLOTEST1POLOTEST4', 'POLOTEST1POLOTEST3', 'POLOTEST1POLOTEST2']
const bitmartBlackList = ['FUTURE-AI']

// расбанить RUNEUSDT, MULTIUSDT, 'MDXUSDT'

module.exports = { binanceArr, mexcArr, bybitArr, gateIoArr, coinbaseArr, lbankArr, kucoinArr, okxArr, bitgetArr, huobiArr, poloniexArr, bitmartArr,       flag, mexcBlackList, binanceBlackList, bybitBlackList, gateIoBlackList, lbankBlackList, kucoinBlackList, huobiBlackList, bitgetBlackList, poloniexBlackList, bitmartBlackList}